name: mydairy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: 3.9.2
  flutter: 3.35.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: 9.1.1
  flutter_slidable: 4.0.3
  get_it: 9.0.5
  go_router: 17.0.0
  hive: 2.2.3
  intl: 0.20.2
  package_info_plus: 9.0.0
  shared_preferences: 2.5.3
  uuid: 4.5.2
  equatable: 2.0.7
  hive_flutter: 1.1.0
  dio: ^5.7.0
  fl_chart: ^0.70.1
  encrypt: ^5.0.3
  local_auth: ^2.3.0
  dartz: ^0.10.1
  table_calendar: ^3.1.2
  screenshot: ^3.0.0
  permission_handler: ^11.3.1
  share_plus: ^10.1.2
  path_provider: ^2.1.5
  image_gallery_saver_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  hive_generator: 2.0.1
  build_runner: 2.4.13
  integration_test:
    sdk: flutter
  flutter_launcher_icons: 0.13.1
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#6366F1"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
